on:
  push:
    branches:
    - main

name: Continuous Integration

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
#       - name: intall playwright dependencies
#         run: npx playwright install-deps

      - name: Install dependencies and run tests
        run: npm install && npm test
