on:
  push:
    branches:
    - main

name: Continuous Integration

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
#       - name: intall playwright dependencies
#         run: npx playwright install-deps

      - name: Install dependencies and run tests
        run: |
          npx playwright install
          npm install && npm test
